export const data = [
  {
    id: 1,
    name: "1917",
    title: "1917",
    year: "1917",
    nation: "UK",
    cost: 300000000,
    img: "../assets/images/1917.jpeg",
    info: "1917 là một bộ phim điện ảnh đề tài chiến tranh sử thi năm 2019 do Sam Mendes đạo diễn kiêm sản xuất và đồng biên kịch",
    trailer: "https://www.youtube.com/embed/lJkiUFGjRe4",
  },
  {
    id: 2,
    name: "Cậu Vàng",
    title: "Cậu Vàng",
    year: "2000",
    nation: "VN",
    img: "../assets/images/cauvang.jpg",
    info: "Hãy cùng Ghiền review phim Cậu Vàng để tìm hiểu xem bộ phim về chú chó Việt nhưng được thể hiện bởi chó Nhật Bản có gì hay ho không nhé!",
    trailer: "https://www.youtube.com/embed/VU_NrOpBRdo",
  },
  {
    id: 3,
    name: "Eternals",
    title: "Eternals",
    year: "2000",
    nation: "USA",
    img: "../assets/images/eternals.jpeg",
    info: "Sau nhiều thế kỉ “ra riêng”, các Eternal phải tập hợp lại cùng tiêu diệt kẻ thù. Và rồi, vẫn như mọi khi, phim Marvel là thứ biến trailer thành cú lừa ngoạn mục ...",
    trailer: "https://www.youtube.com/embed/x_me3xsvDgk",
  },
  {
    id: 4,
    name: "Freedom",
    title: "Freedom",
    year: "2000",
    nation: "USA",
    img: "../assets/images/freedom.jpg",
    info: "Freedom là một bộ phim Mỹ của đạo diễn Peter Cousens",
    trailer: "https://www.youtube.com/embed/rTJXlbEJ0dw",
  },
  {
    id: 5,
    name: "Hunter",
    title: "Hunter",
    year: "2000",
    nation: "USA",
    img: "../assets/images/hunter.jpg",
    info: "Geralt xứ Rivia, một thợ săn quái vật đột biến, dấn thân vào hành trình đến với số phận trong thế giới hỗn loạn mà con người còn ác độc hơn cả quỷ dữ.",
    trailer: "https://www.youtube.com/embed/3od-kQMTZ9M",
  },
  {
    id: 6,
    name: "IT",
    title: "IT",
    year: "2000",
    nation: "USA",
    img: "../assets/images/IT.jpg",
    info: " [PHIM HÀNH ĐỘNG MỸ] CUỘC RƯỢT ĐUỔI NGHẸT THỞ",
    trailer: "https://www.youtube.com/embed/FnCdOQsX5kc",
  },
  {
    id: 7,
    name: "Red",
    title: "Red",
    year: "2000",
    nation: "USA",
    img: "../assets/images/red.jpg",
    info: "Red - Họ từng là những đặc vụ hàng đầu của Cục tình báo trung ương Hoa Kỳ nhưng việc nắm giữ một ...",
    trailer: "https://www.youtube.com/embed/lwjn6sLl4U8",
  },
  {
    id: 8,
    name: "SpiderMan",
    title: "SpiderMan",
    year: "2000",
    nation: "USA",
    img: "../assets/images/spider.jpg",
    info: "Tiếp nối cái kết của Spider-Man: Far From Home, Peter Parker (Tom Holland) và MJ (Zendaya) đã chính thức thành một đôi. · Bản thân “Nhện nhọ” còn ...",
    trailer: "https://www.youtube.com/embed/JfVOs4VSpmA",
  },
  {
    id: 9,
    name: "Thor",
    title: "Thor",
    year: "2000",
    nation: "USA",
    img: "../assets/images/thor.jpeg",
    info: "Tình Yêu Và Sấm Sét. Thor đi vào một cuộc hành trình không giống như bất cứ cuộc phiêu lưu anh ấy từng phải đối mặt, một cuộc tìm kiếm ...",
    trailer: "https://www.youtube.com/embed/Go8nTmfrQd8",
  },
];
